spring:
    profile:
        active:
        - dev
---
spring:
    profiles: dev #开发环境
    application:
        name: microservicecloud-config-hxr-dev
---
spring:
    profile: test #测试环境
    application:
        name: microservicecloud-config-hxr-test
#必须要保存为UTF-8格式，否则会因为乱码报错